<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INLEN8520062597" failures="1" tests="6" name="runner.MyRunner" time="18.536" errors="0" timestamp="2022-09-13T23:50:14 IST" skipped="0">
  <testcase classname="runner.MyRunner" name="runScenario" time="2.822"/>
  <system-out/>
  <testcase classname="runner.MyRunner" name="runScenario" time="2.849">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at stepdefinitions.Checkout.user_clicks_on_continue_button_with_invalid_details(Checkout.java:78)
at âœ½.User clicks on continue button with invalid details(file:///C:/Users/garmitra/eclipse-workspace/SwagLab/src/test/java/features/Checkout.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.MyRunner" name="runScenario" time="3.594"/>
  <system-out/>
  <testcase classname="runner.MyRunner" name="runScenario" time="2.710"/>
  <system-out/>
  <testcase classname="runner.MyRunner" name="runScenario" time="3.795"/>
  <system-out/>
  <testcase classname="runner.MyRunner" name="runScenario" time="2.766"/>
  <system-out/>
</testsuite> <!-- runner.MyRunner -->
